
services:
  accessor:
    build:
      context: .
      dockerfile: VirtualStore.Accessor/Dockerfile
    container_name: accessor
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Northwind;User Id=sa;Password=MyN3wP@ssword;
    depends_on:
      - sqlserver
    networks:
      - virtualstore

  accessor-dapr:
    image: "daprio/daprd:latest"
    container_name: accessor-dapr
    command: [
      "./daprd",
      "-app-id", "accessor",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-port", "3500"
    ]
    volumes:
      - "./components/:/components"
    depends_on:
      - accessor
    network_mode: "service:accessor"

  managers:
    build:
      context: .
      dockerfile: VirtualStore.Managers/Dockerfile
    container_name: managers
    ports:
      - "5001:80"
    environment:
     - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver
    networks:
      - virtualstore

  managers-dapr:
    image: "daprio/daprd:latest"
    container_name: managers-dapr
    command: [
      "./daprd",
      "-app-id", "managers",
      "-app-port", "80",
      "-components-path", "/components",
      "-dapr-http-port", "3501"
    ]
    volumes:
      - "./components/:/components"
    depends_on:
      - managers
    network_mode: "service:managers"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "MyN3wP@ssword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - virtualstore

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - virtualstore

networks:
  virtualstore:
    driver: bridge

volumes:
  sqlserverdata:
